import daisyui from "daisyui";

export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      fontFamily: {
        vt323: ["VT323", "monospace"],
        goldman: ["Goldman", "monospace"],
        neontubes: ["neontubes", "monospace"],
        caveatBrush: ["Caveat Brush", "monospace"],
        indieFlower: ["Indie Flower", "monospace"],
        rajdhani: ["Rajdhani", "monospace"],
      },
      screens: {
        xs: { max: "639px" },
        xxs: { max: "461px" },
        nanoXS: { max: "381px" },
      },
    },
  },
  plugins: [daisyui],
  daisyui: {
    themes: [
      "dark",
      "cupcake",
      "bumblebee",
      "emerald",
      "corporate",
      "synthwave",
      "retro",
      "cyberpunk",
      "valentine",
      "halloween",
      "garden",
      "forest",
      "aqua",
      "lofi",
      "pastel",
      "fantasy",
      "wireframe",
      "black",
      "luxury",
      "dracula",
      "cmyk",
      "autumn",
      "business",
      "acid",
      "lemonade",
      "night",
      "coffee",
      "winter",
      "dim",
      "nord",
      "sunset",
    ],
    darkTheme: "dark",
    base: true,
    styled: true,
    utils: true,
    prefix: "",
    logs: true,
    themeRoot: ":root",
  },
};
